Update cordova-plugin-add-swift-support version
GEDYSIntraWare/cordova-plugin-call-directory pull request #15
Opened 2019-04-02 12:03 UTC by tombell

Updates the required version of cordova-plugin-add-swift-support to ^2.0.0, for the fixes included in the plugin for Cordova CLI 9.x.

2019-04-02 12:08 UTC, NiklasMerz requested changes
Thank you. Please update `package.json`, too.

2019-04-02 14:22 UTC, tombell commented
@NiklasMerz thanks for the heads up, gone ahead and updated that as well.

2019-04-02 14:22 UTC, NiklasMerz approved these changes

2019-04-09 11:34 UTC, NiklasMerz requested changes
Since it is still not merged could you please update to version 2.0.2 for Swift 4 support first.

Thanks. I will merge it then and create a new release.

2019-04-09 12:35 UTC, tombell commented
@NiklasMerz I deleted the fork so I cannot updated this PR, but I'll open a new one using 2.0.2.

2019-04-09 12:35 UTC, closed without merging